### ISSUE TITLE
ruff version update

### ISSUE THREAD

**Issue by patillacode** [sublimelsp/LSP-ruff#18]
Hi!

Thanks for this project!

A bit of context:

- I am really interested in some of the recently added features in `ruff` and they are only available in version `0.0.263`

- I did a bit of research and noticed the version of `ruff` within `LSP-ruff` is `0.0.253` and that is why my `ruff` config was not working properly.

- I created this PR at [charliermarsh/ruff-lsp](https://github.com/charliermarsh/ruff-lsp/pull/101) in case that is the way (**please read**)

Questions:

Am I approaching this the right way?

Is there a less convoluted way for me to point the executable to my local version of `ruff` while versions catch up? 

I tried to do it via the `path` setting but I guess I am doing it wrong:

This is one of my last (unsuccessful) tries the `LSP-ruff.sublime-settings` file:
```
{
	"initializationOptions": {
        "globalSettings": {
            // same as settings
            "path": ["/usr/local/bin/ruff"],
        },
    },
}

```

That's it, I'll patiently wait for a response!

**Comment by rchl** [comment]
Updating `ruff` dependency in `ruff-lsp` as you did is the way to go. We'll get dependabot notification at some point later and will bump the `ruff` version through that.

As far as using custom ruff binary, this seems to work for me:

```jsonc
// Settings in here override those in "LSP-ruff/LSP-ruff.sublime-settings"
{
    "initializationOptions": {
        "settings": {
            "path": ["/opt/homebrew/bin/ruff"]
        },
    }
}
```

Not sure why `globalSettings` doesn't work.

**Comment by rchl** [comment]
Fixing the issue with not respecting `globalSettings` in https://github.com/sublimelsp/LSP-ruff/pull/19

**Comment by patillacode** [comment]
Great, thanks!

I could swear I had tried your example settings and it failed, but it is now working!

**Comment by rchl** [comment]
Released https://github.com/sublimelsp/LSP-ruff/releases/tag/1.0.5
