### ISSUE TITLE
ensurepip does not exist as standalone program

### ISSUE THREAD

**Issue by edaqa-uncountable** [sublimelsp/LSP-ruff#30]
On recent Ubuntu installs, the `ensurepip` program does not exist in Python3.11. It needs to be called as `python -m ensurepip`. This precents the ruff package from setting up correctly.

**Comment by LDAP** [comment]
Can you provide Sublime Text logs, error messages and such?

**Comment by rchl** [comment]
Closing due to no response.
We are not calling `ensurepip` anyway. Maybe `pip` does but that's out of our control.
