### ISSUE TITLE
Means to view project-wide diagnostics?

### ISSUE THREAD

**Issue by jgbishop** [sublimelsp/LSP-ruff#31]
In Sublime Text, I'd love to have a way to see ruff's findings for all of the files within my project. At the moment, I don't see such a feature (though maybe I'm missing it). Is such a thing supported? All I see is file-by-file results (as I'm viewing the file).

The SublimeLinter package (using flake8) allows doing this, and it's a feature I miss having.

**Comment by rchl** [comment]
You should report and discuss it in https://github.com/astral-sh/ruff-lsp.

(Though personally I would say this is more of a CI/commit hook job)

**Comment by rchl** [comment]
This project is just a wrapper around https://github.com/astral-sh/ruff-lsp. It's the ruff-lsp that would have to run that command and expose all diagnostics. Nothing can be done here.

**Comment by jgbishop** [comment]
Thanks for the clarification!
