### ISSUE TITLE
How to set max number of characters per line?

### ISSUE THREAD

**Issue by vgoklani** [sublimelsp/LSP-ruff#44]
Hey there,

I just did the update on sublime for ruff-lsp, thank you for the black integration!

I noticed that my code now goes beyond the usual 88 characters. I previously used 

    https://github.com/thep0y/python-black

which automatically rewrote my python code if it extended beyond the limit. Is there a setting in ruff for this? thanks!

**Comment by rchl** [comment]
Probably best way to configure this is through configuration files in your project. See awesome ruff documentation like https://docs.astral.sh/ruff/formatter/

**Comment by vgoklani** [comment]
thanks @rchl 

where should that file be located?

Shouldn't the settings be in: Settings -> Package Settings -> LSP -> Servers -> LSP-ruff ?

**Comment by rchl** [comment]
And you can also do that globally from LSP-ruff settings. Just look on the left column after opening settings and match that structure in your local configuration, adding format options as needed.
