### ISSUE TITLE
Support for Ruff 0.2.0

### ISSUE THREAD

**Issue by Tenzer** [sublimelsp/LSP-ruff#52]
Would it be possible to make a new release with ruff-lsp 0.0.51? It adds support for Ruff 0.2.0 which has been released: https://github.com/astral-sh/ruff-lsp/releases/tag/v0.0.51.

Without it, LSP-ruff refuses to format files if Ruff 0.2.0 has been installed because ruff-lsp checks the upper bound of the Ruff version installed.

**Comment by LDAP** [comment]
Its on my todo for next week :)

**Comment by Tenzer** [comment]
I guess there's no tests, so it might require manual testing?

**Comment by LDAP** [comment]
It's checking/updating the settings and schema and manual testing. Bumping the version itself is done by dependabot #53.

**Comment by LDAP** [comment]
Pushed an update just now

**Comment by Tenzer** [comment]
Thank you! We'll just have to wait until Package Control picks up the new version then, right?

**Comment by LDAP** [comment]
Right. Might take a few hours.
