### ISSUE TITLE
Adding the option to format the selection in addition to format file

### ISSUE THREAD

**Issue by seperman** [sublimelsp/LSP-ruff#56]
Hello,
Is it possible to add the option to format the selection?
Currently, we can only format the whole file.
Thanks

**Comment by jfcherng** [comment]
looks good to me?
![image](https://github.com/sublimelsp/LSP-ruff/assets/6594915/42d8dc2a-5bf7-46cc-b919-bb10d74395f5)

**Comment by seperman** [comment]
My menu looks very different than yours. How come?
![image](https://github.com/sublimelsp/LSP-ruff/assets/2314797/c9468a43-a5c4-4f32-9467-866cce1743ed)

**Comment by jfcherng** [comment]
Are you still  using ST 3?

**Comment by seperman** [comment]
I'm on Sublime build 4169. So I assume it is ST 4?

**Comment by jfcherng** [comment]
Yes that's ST 4. Or maybe a very outdated LSP...?

**Comment by jfcherng** [comment]
Looks good. I just tried a clean portable ST but it still works on my side. So I have no idea what's happening here.

I do see a payload

> :: [02:46:07.137] --> LSP-ruff textDocument/rangeFormatting (5): {'textDocument': {'uri': 'file:///xxx.py'}, 'options': {'insertSpaces': True, 'insertFinalNewline': True, 'tabSize': 4, 'trimFinalNewlines': True, 'trimTrailingWhitespace': True}, 'range': {'end': {'character': 0, 'line': 1}, 'start': {'character': 0, 'line': 0}}, 'workDoneToken': '$ublime-work-done-progress-5'}

**Comment by rchl** [comment]
The version of ruff that you were using likely didn't support it yet. That's why it's safest to use the bundled version.

**Comment by seperman** [comment]
Ok thanks. I'm happy the selection format works now.
