### ISSUE TITLE
Linting to only trigger on demand and/or while saving?

### ISSUE THREAD

**Issue by jklaiho** [sublimelsp/LSP-ruff#67]
I would love the ability to only trigger linting when I hit a specific key combo, instead of automatically while I'm typing. The linting errors and warnings that pop up while typing code that will eventually be valid are annoying and distracting, IMHO. I ended up ignoring W293 to stop the worst offender: Ruff nagging me about whitespace on an empty line when I press Enter and get auto-indentation.

In addition, an option to lint automatically when saving would be really nice. Ruff seems to have a VS Code specific setting called `lint.run`, which you can set to `onSave` instead of `onType`. Would something like this be possible to implement for LSP-ruff?

I've looked through a bunch of docs and haven't found an option for either of these; sorry if I've missed something.

**Comment by rchl** [comment]
That's more of a request for the core LSP package and there already is a request like that: https://github.com/sublimelsp/LSP/issues/2161

**Comment by rchl** [comment]
Since we have issue in LSP, this one is redundant.

The keybinding you are looking for would look something like:

```
    {
        "keys": ["super+ctrl+i"],
        "command": "lsp_code_actions",
        "args": {"only_kinds": ["source"]},
        "context": [{"key": "lsp.session_with_capability", "operand": "codeActionProvider.codeActionKinds"}]
    },
```

You can find that example in the default LSP keybindings (commented out).
