### ISSUE TITLE
Add quick action to ignore line

### ISSUE THREAD

**Issue by Gabriel-p** [sublimelsp/LSP-ruff#84]
Currently to ignore a line one has to manually add a `# noqa`  comment. This could be added as a quick action in the pop-up message.

For example this is what [SublimeLinter-flake8](https://github.com/SublimeLinter/SublimeLinter-flake8) looks like:

![Captura de pantalla de 2024-10-03 18 43 55](https://github.com/user-attachments/assets/6947296d-8fdb-4ae1-b36c-a5577d466a1a)

clicking on the blue arrow triggers:

    import scienceplots  # noqa: F401

**Comment by rchl** [comment]
This is already supported through code action.

https://github.com/user-attachments/assets/655993d2-bcda-40e7-95e5-f5ede5361c4c

You can trigger code actions in multiple ways - from the popup, through right click, menus or keyboard shortcut (needs to be manually assigned).

**Comment by Gabriel-p** [comment]
You are correct, don't know how I missed that. Thank you
