### ISSUE TITLE
LSP-ruff on Windows: How to Set Python Interpreter Path

### ISSUE THREAD

**Issue by andypal333** [sublimelsp/LSP-ruff#88]
I am using `LSP` and `LSP-ruff` packages in Sublime Text on Windows and encounter the following issues:

When I open Sublime Text, LSP-ruff fails to start with the error:

![sublime_text_Dqd8atb5Gm](https://github.com/user-attachments/assets/8efdece7-0e5f-415c-b31e-14cc215ce99d)

Questions:
- How can I specify the absolute path to a Python interpreter in `LSP-ruff.sublime-settings` to ensure LSP-ruff can find it?
- What settings should I add in `LSP-Ruff.sublime-settings` to enable LSP-ruff to provide code completions in Sublime Text?

Thank you for any guidance on configuring these settings!

**Comment by rchl** [comment]
This should be fixed in the latest version of lsp-utils dependency. Try restarting ST to trigger the update.

**Comment by andypal333** [comment]
> This should be fixed in the latest version of lsp-utils dependency. Try restarting ST to trigger the update.

Doesn't work i tried restarting it several times.

**Comment by rchl** [comment]
Try explicitly triggering update with "Package Control: Satisfy dependencies" (or "Package Control: Upgrade Package") form the command palette.

**Comment by andypal333** [comment]
@rchl Thanks a lot this fixed the issue! Last question, can i configure LSP-ruff to provide code completions in Sublime Text?

**Comment by rchl** [comment]
No, ruff is a linter, it doesn't provide code intelligence. Try `LSP-pyright` for that.
